# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  server:
    depends_on: 
      - db 
    build:
      context: .
    secrets:
      - db-password
      - api-key
    environment:
      - API_KEY=/run/secrets/api-key
      - POSTGRES_PASSWORD=/run/secrets/db-password
    ports:
      - 3000:3000
    develop:
      watch:
        - action: rebuild
          path: .
  db:
    image: postgres:12.18
    user: postgres
    secrets:
      - db-password
    environment:
      - POSTGRES_PASSWORD=/run/secrets/db-password
    ports:
      - 5431:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  db-data:
secrets:
  db-password:
    file: credentials/db_password.txt
  api-key:
    file: credentials/api_key.txt
