name: ci


on:
    push:
      paths:
        - 'ContainerizedRepo/DockerfileCR'
        - '.github/workflows/main.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "dockersales/yusuf-basic-nlp"

      - name: Meta
          id: meta
          uses: docker/metadata-action@v3
          with:
            images: demonstrationorg/basic
            tags: |
              type=ref,event=branch
              type=ref,event=pr
              type=semver,pattern={{version}}
              type=sha
      


        - name: Build and push Docker image
            id: build-and-push
            uses: docker/build-push-action@v5
            with:
            sbom: ${{ github.event_name != 'pull_request' }}
            provenance: ${{ github.event_name != 'pull_request' }}
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
            context: .
            platforms: linux/amd64,linux/arm64